### PR TITLE
Added two Key Vault and Identity information in the documentation

### PR DESCRIPTION
**Pull request by gunjandesai**
My last check-in for two new endpoints removed after last check-in, so i submitted new checked-in for both endpoints

### CODE REVIEW

**Comment by PRMerger12** [comment]
@gunjandesai : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by orspod** [comment]
@basaba - please review. Thanks!

**Comment by orspod** [comment]
@basaba please review

**Comment by orspod** [comment]
@gunjandesai - closing as per @basaba's request

**Pull request closed without merging**
