### PR TITLE
Update write-queries.md

### PR DESCRIPTION
**Pull request by airmelt-ms**
using single quotation mark can't generate anything.
It will not meet anyone's expect.

like this pic below:
image

### CODE REVIEW

**Comment by airmelt-ms** [comment]
@openpublish

**Comment by shsagir** [comment]
Learn Build status updates of commit _[2ee7a66](https://github.com/airmelt-ms/dataexplorer-docs/commits/2ee7a6650bc776455fcdadcb4f13456094546217)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[data-explorer/write-queries.md](https://github.com/airmelt-ms/dataexplorer-docs/blob/patch-1/data-explorer/write-queries.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/44fbb50c-a02d-79e7-9b6a-0040a309a8dd/202212130754347518-1537/BuildReport?accessString=fcf71cc9c5d391496c6de99b84a1544ca40d6ebfa670bfdf05552ff61d1b3121).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/44fbb50c-a02d-79e7-9b6a-0040a309a8dd?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by Court72** [comment]
@shsagir

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by YaelSchuster** [comment]
Thanks @airmelt-ms, you are correct. Strings need to be encased in double quotation marks, not single ones.

**Pull request merged**
