### PR TITLE
Added missing table name input

### PR DESCRIPTION
**Pull request by grik001**
Added missing table name input

### CODE REVIEW

**Comment by PRMerger15** [comment]
@grik001 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by YaelSchuster** [comment]
Hi @grik001 thanks so much for your contribution.
@kerend please review

**Review by vladikbr — APPROVED** [review]

**Comment by vladikbr** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@vladikbr: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by YaelSchuster** [comment]
Hi @PRMerger8 @vladikbr is on the product team
#sign-off

**Comment by PRMerger19** [comment]
@YaelSchuster: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
