### PR TITLE
Update show-cluster-capacity-policy-command.md

### PR DESCRIPTION
**Pull request by Savionat**
Fix to align with actual (and desired) behavior

### CODE REVIEW

**Comment by PRMerger13** [comment]
@Savionat : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Savionat** [comment]
#Sign Off

**Comment by Savionat** [comment]
#sign-off

**Comment by PRMerger3** [comment]
@Savionat: I'm sorry - only the author of this article, @shsagir, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by shsagir** [comment]
#sign-off

**Pull request merged**
