### PR TITLE
Update sandbox docs

### PR DESCRIPTION
**Pull request by omerblum**
Update sandbox docs

### CODE REVIEW

**Comment by shsagir** [comment]
Learn Build status updates of commit _[bba33a8](https://github.com/omerblum/dataexplorer-docs/commits/bba33a8ceb7a053e9cc7f79622643b3ea3ae3ad1)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[data-explorer/cluster-encryption-double.md](https://github.com/omerblum/dataexplorer-docs/blob/omer/update-sandbox-doc/data-explorer/cluster-encryption-double.md) | :warning:Warning | | [Details](#user-content-c46a5e493c2b10c7f9f7aa02613cb8e7-cd2bb28d)
[data-explorer/kusto/concepts/sandboxes.md](https://github.com/omerblum/dataexplorer-docs/blob/omer/update-sandbox-doc/data-explorer/kusto/concepts/sandboxes.md) | :warning:Warning | | [Details](#user-content-20a06462b15b1f1dbcbe150d7a0e78bb-cd2bb28d)
[data-explorer/kusto/concepts/sandboxes-in-non-modern-skus.md](https://github.com/omerblum/dataexplorer-docs/blob/omer/update-sandbox-doc/data-explorer/kusto/concepts/sandboxes-in-non-modern-skus.md) | :warning:Warning | | [Details](#user-content-2c08d4c3eccd85679ae8d62680364e55-cd2bb28d)
[data-explorer/kusto/management/toc.yml](https://github.com/omerblum/dataexplorer-docs/blob/omer/update-sandbox-doc/data-explorer/kusto/management/toc.yml) | :white_check_mark:Succeeded | |

<a id="c46a5e493c2b10c7f9f7aa02613cb8e7-cd2bb28d"></a>
### [data-explorer/cluster-encryption-double.md](https://github.com/omerblum/dataexplorer-docs/blob/omer/update-sandbox-doc/data-explorer/cluster-encryption-double.md)
 - **Line 111, Column 57**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#virtual-machine-sizes' in 'kusto/concepts/sandboxes.md'.`````

<a id="20a06462b15b1f1dbcbe150d7a0e78bb-cd2bb28d"></a>
### [data-explorer/kusto/concepts/sandboxes.md](https://github.com/omerblum/dataexplorer-docs/blob/omer/update-sandbox-doc/data-explorer/kusto/concepts/sandboxes.md)
 - **Line 16, Column 25**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#Modern-Virtual-machine-sizes' in 'kusto/concepts/sandboxes.md', did you mean '#modern-virtual-machine-sizes'?`````

<a id="2c08d4c3eccd85679ae8d62680364e55-cd2bb28d"></a>
### [data-explorer/kusto/concepts/sandboxes-in-non-modern-skus.md](https://github.com/omerblum/dataexplorer-docs/blob/omer/update-sandbox-doc/data-explorer/kusto/concepts/sandboxes-in-non-modern-skus.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/44fbb50c-a02d-79e7-9b6a-0040a309a8dd/202212111532419612-1532/BuildReport?accessString=9fa7fecd9ac42fe3caefbef5ae4eeb6d659ccefab6f549660fdd87be05ac47a7).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/44fbb50c-a02d-79e7-9b6a-0040a309a8dd?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by shsagir** [comment]
Learn Build status updates of commit _[6869e41](https://github.com/omerblum/dataexplorer-docs/commits/6869e41f0bdec595e8de5c07e2eba75057f7f4d0)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[data-explorer/cluster-encryption-double.md](https://github.com/omerblum/dataexplorer-docs/blob/omer/update-sandbox-doc/data-explorer/cluster-encryption-double.md) | :warning:Warning | | [Details](#user-content-c46a5e493c2b10c7f9f7aa02613cb8e7-73e531a9)
[data-explorer/kusto/concepts/sandboxes.md](https://github.com/omerblum/dataexplorer-docs/blob/omer/update-sandbox-doc/data-explorer/kusto/concepts/sandboxes.md) | :warning:Warning | | [Details](#user-content-20a06462b15b1f1dbcbe150d7a0e78bb-73e531a9)
[data-explorer/kusto/concepts/sandboxes-in-non-modern-skus.md](https://github.com/omerblum/dataexplorer-docs/blob/omer/update-sandbox-doc/data-explorer/kusto/concepts/sandboxes-in-non-modern-skus.md) | :warning:Warning | | [Details](#user-content-2c08d4c3eccd85679ae8d62680364e55-73e531a9)
[data-explorer/kusto/management/toc.yml](https://github.com/omerblum/dataexplorer-docs/blob/omer/update-sandbox-doc/data-explorer/kusto/management/toc.yml) | :white_check_mark:Succeeded | |

<a id="c46a5e493c2b10c7f9f7aa02613cb8e7-73e531a9"></a>
### [data-explorer/cluster-encryption-double.md](https://github.com/omerblum/dataexplorer-docs/blob/omer/update-sandbox-doc/data-explorer/cluster-encryption-double.md)
 - **Line 111, Column 57**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#virtual-machine-sizes' in 'kusto/concepts/sandboxes.md'.`````

<a id="20a06462b15b1f1dbcbe150d7a0e78bb-73e531a9"></a>
### [data-explorer/kusto/concepts/sandboxes.md](https://github.com/omerblum/dataexplorer-docs/blob/omer/update-sandbox-doc/data-explorer/kusto/concepts/sandboxes.md)
 - **Line 16, Column 25**: **[Warning: bookmark-not-found]** `````Cannot find bookmark '#Modern-Virtual-machine-sizes' in 'kusto/concepts/sandboxes.md', did you mean '#modern-virtual-machine-sizes'?`````

<a id="2c08d4c3eccd85679ae8d62680364e55-73e531a9"></a>
### [data-explorer/kusto/concepts/sandboxes-in-non-modern-skus.md](https://github.com/omerblum/dataexplorer-docs/blob/omer/update-sandbox-doc/data-explorer/kusto/concepts/sandboxes-in-non-modern-skus.md)
 - **Line 0, Column 0**: **[Warning: h1-missing - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/h1-missing?branch=main)]** `````H1 is required. Use a single hash (#) followed by a space to create your top-level heading.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/44fbb50c-a02d-79e7-9b6a-0040a309a8dd/202212111541516751-1532/BuildReport?accessString=1bc4a53162961225e52117dc1e05abdc876b36c679ebb2257eedf43295b35fb8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/44fbb50c-a02d-79e7-9b6a-0040a309a8dd?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by shsagir** [comment]
Learn Build status updates of commit _[9a39654](https://github.com/omerblum/dataexplorer-docs/commits/9a39654fd6f21b1e9690f0ff8397cf6a68ffe225)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[data-explorer/cluster-encryption-double.md](https://github.com/omerblum/dataexplorer-docs/blob/omer/update-sandbox-doc/data-explorer/cluster-encryption-double.md) | :white_check_mark:Succeeded | |
[data-explorer/kusto/concepts/sandboxes.md](https://github.com/omerblum/dataexplorer-docs/blob/omer/update-sandbox-doc/data-explorer/kusto/concepts/sandboxes.md) | :white_check_mark:Succeeded | |
[data-explorer/kusto/concepts/sandboxes-in-non-modern-skus.md](https://github.com/omerblum/dataexplorer-docs/blob/omer/update-sandbox-doc/data-explorer/kusto/concepts/sandboxes-in-non-modern-skus.md) | :white_check_mark:Succeeded | |
[data-explorer/kusto/management/toc.yml](https://github.com/omerblum/dataexplorer-docs/blob/omer/update-sandbox-doc/data-explorer/kusto/management/toc.yml) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/44fbb50c-a02d-79e7-9b6a-0040a309a8dd/202212111603150364-1532/BuildReport?accessString=2fead59edf2635f26bc9857faa2e934111c3cca1776bd9e131167e87c8e643f2).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/44fbb50c-a02d-79e7-9b6a-0040a309a8dd?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by omerblum** [comment]
@microsoft-github-policy-service agree [company="{Microsoft}"]

**Comment by omerblum** [comment]
@microsoft-github-policy-service agree

**Comment by adieldar** [comment]
@shsagir - I usually review doc using the preview URLs, but they are missing for this PR. Why? can this be fixed?

**Comment by YaelSchuster** [comment]
@adieldar this is on the public repo, so there is no build staging. (This is why MS employees generally aren't allowed to make changes in the private repo). I can pull the branch and reopen a private PR if we need.

**Comment by shsagir** [comment]
> @adieldar this is on the public repo, so there is no build staging. (This is why MS employees generally aren't allowed to make changes in the private repo). I can pull the branch and reopen a private PR if we need.

@yael Handled, thx

**Pull request closed without merging**
