### PR TITLE
Update renderoperator.md

### PR DESCRIPTION
**Pull request by ciufudean**
`linechart` is not supported as a `render `visualization, at least in my version of Log Analytics portal

### CODE REVIEW

**Comment by PRMerger7** [comment]
@ciufudean : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ciufudean** [comment]
It may be a limitation with Log Analytics, as I am trying to run this example and it says it is not supported. In which case the documentation should mention the limitations in Log Analytics.

```
range x from -2 to 2 step 0.1
| extend sin = sin(x), cos = cos(x)
| extend x_sign = iif(x > 0, "x_pos", "x_neg")
| extend sum_sign = iif(sin + cos > 0, "sum_pos", "sum_neg")
| render linechart with  (ycolumns = sin, cos, series = x_sign, sum_sign)
```

**Comment by orspod** [comment]
@ciufudean - The render documentation has two pivots depending upon your service (Azure Data Explorer or Azure Monitor).
If you select Azure Monitor aka Log Analytics (https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/renderoperator?pivots=azuremonitor), the documentation doesn't contain linechart as a supported option.
Closing this PR.

**Comment by ciufudean** [comment]
I missed previous comment, but I've discovered the documentation pivots myself now

**Pull request closed without merging**
