### PR TITLE
Update create-cluster-database-python.md

### PR DESCRIPTION
**Pull request by yihezkel**
See https://github.com/MicrosoftDocs/dataexplorer-docs/issues/1141

### CODE REVIEW

**Comment by PRMerger12** [comment]
@yihezkel : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by shsagir** [comment]
Fixes https://github.com/MicrosoftDocs/dataexplorer-docs/issues/1141

**Comment by shsagir** [comment]
#sign-off
@yihezkel: Thx. Please make such changes via the private repo :-)

**Review by shsagir — APPROVED** [review]

**Comment by shsagir** [comment]
#sign-off

**Pull request merged**
