### PR TITLE
Update stop cluster recommendation

### PR DESCRIPTION
**Pull request by guregini**

### CODE REVIEW

**Comment by PRMerger-2** [comment]
@guregini : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by YaelSchuster — APPROVED** [review]

**Comment by PRMerger16** [comment]
@guregini : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by guregini** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@guregini: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by YaelSchuster** [comment]
Approved by ADX docs team
#sign-off

**Comment by PRMerger4** [comment]
@YaelSchuster: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by orspod** [comment]
#sign-off

**Pull request merged**
