### PR TITLE
Update unionoperator.md

### PR DESCRIPTION
**Pull request by guywi-ms**

### CODE REVIEW

**Comment by shsagir** [comment]
Learn Build status updates of commit _[a752f46](https://github.com/guywi-ms/dataexplorer-docs/commits/a752f464f4043d66d21f1cb49808f3b62ac3ad92)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[data-explorer/kusto/query/unionoperator.md](https://github.com/guywi-ms/dataexplorer-docs/blob/patch-1/data-explorer/kusto/query/unionoperator.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/44fbb50c-a02d-79e7-9b6a-0040a309a8dd/202212121520184780-1534/BuildReport?accessString=707d56fa30aedef5b52d4277609b582d1474b4f144569e49957336f94b6acf66).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/44fbb50c-a02d-79e7-9b6a-0040a309a8dd?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by guywi-ms** [comment]
#assign-reviewer: @rofrenke

**Comment by shsagir** [comment]
Learn Build status updates of commit _[8c23152](https://github.com/guywi-ms/dataexplorer-docs/commits/8c23152b06e61aa25db587e110f980b19ce9aa83)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[data-explorer/kusto/query/unionoperator.md](https://github.com/guywi-ms/dataexplorer-docs/blob/patch-1/data-explorer/kusto/query/unionoperator.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/44fbb50c-a02d-79e7-9b6a-0040a309a8dd/202212121527526857-1534/BuildReport?accessString=3018d70afcf92fd1695dfdc83da45fa431a0a2d7ee4c9ea08512419e08326784).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/44fbb50c-a02d-79e7-9b6a-0040a309a8dd?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by shsagir** [comment]
Learn Build status updates of commit _[f9c6594](https://github.com/guywi-ms/dataexplorer-docs/commits/f9c6594cc070f8895329d5661c590504bfb18926)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[data-explorer/kusto/query/unionoperator.md](https://github.com/guywi-ms/dataexplorer-docs/blob/patch-1/data-explorer/kusto/query/unionoperator.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/44fbb50c-a02d-79e7-9b6a-0040a309a8dd/202212121558100060-1534/BuildReport?accessString=138641baf7b56fc2d7aedf2b4bba53b860987dd53c2f08f86e84c756d1d537a6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/44fbb50c-a02d-79e7-9b6a-0040a309a8dd?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by guywi-ms** [comment]
#sign-off

**Comment by Jak-MS** [comment]
@guywi-ms - you might want to use the private repo for these changes since you can sign off there.

@shsagir 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by YaelSchuster** [comment]
Approved by ADX content team

#sign-off

**Pull request merged**
