### PR TITLE
when2use section

### PR DESCRIPTION
**Pull request by yodobrin**
Suggesting adding a sub section calling out specifically the main factors in choosing ADX.  This will help readers reach the decision faster. While the content is mostly already part of the doc, customers and engineers are having a hard time searching for the criteria.

### CODE REVIEW

**Comment by PRMerger19** [comment]
@yodobrin : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger5** [comment]
The following users don't have valid GitHub IDs, or are not collaborators on this repo: microsoftdocs/public-repo-pr-review-team

**Comment by shsagir** [comment]
@yodobrin Thanks for contacting us with feedback about our product documentation. Depending on the complexity, it could take from a few business days to a few weeks to look further into your question, issue, or suggestion. We'll contact you if we need further information, and you'll receive an email message each time we "@mention" you in a comment.

Thanks again for submitting your feedback. Your suggestions help improve our documentation.

**Comment by YaelSchuster** [comment]
closing in order to reopen on private repo
#please-close

**Pull request closed without merging**
