### PR TITLE
Update pythonplugin.md

### PR DESCRIPTION
**Pull request by rygao-msft**
Fix name of argument: script_parameters -> script_arguments

### CODE REVIEW

**Comment by PRMerger9** [comment]
@rygao-msft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by shsagir** [comment]
Docs Build status updates of commit _[83883b7](https://github.com/rygao-msft/dataexplorer-docs/commits/83883b70429ca091a656f37581f9a4a3cdcfbb5d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[data-explorer/kusto/query/pythonplugin.md](https://github.com/rygao-msft/dataexplorer-docs/blob/patch-1/data-explorer/kusto/query/pythonplugin.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/44fbb50c-a02d-79e7-9b6a-0040a309a8dd/202208110117482088-1350/BuildReport?accessString=eac236f2fa302fa9bc916614127af8ed34ad863ae6dd72da84e3b6c61502ec32).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/44fbb50c-a02d-79e7-9b6a-0040a309a8dd?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by Jak-MS** [comment]
@shsagir - Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by YaelSchuster** [comment]
SME recommends changing line 27 to script_parameters instead. Closing this PR and will open new one for this fix.

#please-close

**Comment by rygao-msft** [comment]
> 

OK - FYI, only `script_arguments` works for me in ADX/Kusto.

**Pull request closed without merging**
