### PR TITLE
Put an actual working example

### PR DESCRIPTION
**Pull request by samlevy-microsoft**
Put an actual working example

### CODE REVIEW

**Comment by PRMerger5** [comment]
@samlevy-microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by shsagir** [comment]
Docs Build status updates of commit _[3a785e0](https://github.com/samlevy-microsoft/dataexplorer-docs/commits/3a785e0eab0cf1109f36e8ca8efc664df7b40274)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[data-explorer/kusto/api/powershell/powershell.md](https://github.com/samlevy-microsoft/dataexplorer-docs/blob/patch-5/data-explorer/kusto/api/powershell/powershell.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/44fbb50c-a02d-79e7-9b6a-0040a309a8dd/202208020823358409-1340/BuildReport?accessString=5277b499cf2cc4be097141ea1a7a9ccb0090bf169a7a385dd2f1094d8903281e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/44fbb50c-a02d-79e7-9b6a-0040a309a8dd?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by YaelSchuster** [comment]
#sign-off

Approved by ADX content and dev teams

**Comment by PRMerger17** [comment]
Invalid command: '#sign-off'. Only the assigned author of one or more file in this PR can sign off. @shsagir

**Comment by shsagir** [comment]
Docs Build status updates of commit _[3a785e0](https://github.com/samlevy-microsoft/dataexplorer-docs/commits/3a785e0eab0cf1109f36e8ca8efc664df7b40274)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[data-explorer/kusto/api/powershell/powershell.md](https://github.com/samlevy-microsoft/dataexplorer-docs/blob/patch-5/data-explorer/kusto/api/powershell/powershell.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/44fbb50c-a02d-79e7-9b6a-0040a309a8dd/202208021505260371-1340/BuildReport?accessString=064518e4433bbcf0214e15adacc5901f473f6b8d5c3a5cfcb08421ab8347036e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/44fbb50c-a02d-79e7-9b6a-0040a309a8dd?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
