### PR TITLE
Update updatepolicy.md

### PR DESCRIPTION
**Pull request by WilkoAlten**
Deleted ``` in step 5 of the example

### CODE REVIEW

**Comment by PRMerger12** [comment]
@WilkoAlten : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
@shsagir 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by shsagir** [comment]
#sign-off

**Comment by shsagir** [comment]
Docs Build status updates of commit _[ad2c60c](https://github.com/WilkoAlten/dataexplorer-docs/commits/ad2c60c4e93c27289974882d1539a619f59f22e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[data-explorer/kusto/management/updatepolicy.md](https://github.com/WilkoAlten/dataexplorer-docs/blob/patch-1/data-explorer/kusto/management/updatepolicy.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/44fbb50c-a02d-79e7-9b6a-0040a309a8dd/202208011438109455-1333/BuildReport?accessString=6a29697f6dd38059509b9d85c973b8ab8605cce82975703471e12235d5b01934).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/44fbb50c-a02d-79e7-9b6a-0040a309a8dd?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Pull request merged**
