### PR TITLE
Corecting wrong python code

### PR DESCRIPTION
**Pull request by kaareseras**
Corrected lowercase to uppercase and mappingReference to ingestion_mapping_reference

### CODE REVIEW

**Comment by PRMerger9** [comment]
@kaareseras : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by shsagir** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@shsagir: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by shsagir** [comment]
Reviewed by Docs team, please merge

**Pull request merged**
