### PR TITLE
Missing "=" in example

### PR DESCRIPTION
**Pull request by etsaduryananthill**

### CODE REVIEW

**Comment by shsagir** [comment]
Docs Build status updates of commit _[cae1c8a](https://github.com/etsaduryananthill/dataexplorer-docs/commits/cae1c8ad838c133bc3834a9e8fe054c1b18ee60e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[data-explorer/kusto/query/samples.md](https://github.com/etsaduryananthill/dataexplorer-docs/blob/patch-1/data-explorer/kusto/query/samples.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/44fbb50c-a02d-79e7-9b6a-0040a309a8dd/202208250933119153-1368/BuildReport?accessString=ca300336a5a3e23957c953883d24f7667195539199623079f1d939eab2f79d07).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/44fbb50c-a02d-79e7-9b6a-0040a309a8dd?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Comment by Jak-MS** [comment]
@sloutsky 
- Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by sloutsky** [comment]
#sign-off

**Comment by shsagir** [comment]
#sign-off

**Review by shsagir — APPROVED** [review]

**Comment by shsagir** [comment]
#sign-off

**Pull request merged**
