### PR TITLE
Fix code type (from kusto to csharp).

### PR DESCRIPTION
**Pull request by Emeka-MSFT**
Fix a minor typo: code block shows `c#` code (but is labelled was `kusto`).

### CODE REVIEW

**Comment by PRMerger15** [comment]
@Emeka-MSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by shsagir** [comment]
Reviewed by Docs
#sign-off

**Comment by PRMerger19** [comment]
@shsagir: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
