### PR TITLE
must not should be

### PR DESCRIPTION
**Pull request by chwunder**
nothing beside datetime is accepted, so i assume we should make it more easy for customers

### CODE REVIEW

**Comment by PRMerger7** [comment]
@chwunder : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by YaelSchuster** [comment]
Thanks @chwunder for contributing to our docs!

Change approved by ADX content team
#sign-off

**Comment by PRMerger15** [comment]
@YaelSchuster: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
