### PR TITLE
Fix Hyperlink to alter-cluster command

### PR DESCRIPTION
**Pull request by akshay9**
Fixed the typo in the hyperlink

### CODE REVIEW

**Comment by shsagir** [comment]
Learn Build status updates of commit _[447830c](https://github.com/akshay9/dataexplorer-docs/commits/447830c115be6e8a57f0f96f706b2b286981ce6a)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[data-explorer/kusto/management/capacitypolicy.md](https://github.com/akshay9/dataexplorer-docs/blob/patch-1/data-explorer/kusto/management/capacitypolicy.md) | :warning:Warning | | [Details](#user-content-57324b8fb00135c2e2dc0c38050f5641-9e1a6d83)

<a id="57324b8fb00135c2e2dc0c38050f5641-9e1a6d83"></a>
### [data-explorer/kusto/management/capacitypolicy.md](https://github.com/akshay9/dataexplorer-docs/blob/patch-1/data-explorer/kusto/management/capacitypolicy.md)
 - **Line 178, Column 7**: **[Warning: file-not-found - [See documentation](https://review.learn.microsoft.com/help/contribute/validation-ref/file-not-found?branch=main)]** `````Invalid file link: './alter-cluster-capacity-policy-command.md'.`````

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/44fbb50c-a02d-79e7-9b6a-0040a309a8dd/202301060943291828-1564/BuildReport?accessString=55fff9673895ba2ebf6a9d0a3127a49834b89f75ca64cc65942fd9c561a27ac8).

If you see build warnings/errors with permission issues, it might be due to single sign-on (SSO) enabled on Microsoft's GitHub organizations. Please follow instructions [here](https://review.learn.microsoft.com/en-us/help/onboard/sso-troubleshooting?branch=main) to re-authorize your GitHub account to Learn Build.

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/44fbb50c-a02d-79e7-9b6a-0040a309a8dd?tabName=brokenlinks).

**Note:** Your PR may contain errors or warnings or suggestions unrelated to the files you changed. This happens when external dependencies like GitHub alias, Microsoft alias, cross repo links are updated. Please use these [instructions](https://review.learn.microsoft.com/en-us/help/onboard/faq?branch=main&tabs=pr-validation-error-solution#q-why-do-i-get-pr-validation-result-with-cryptic-error-or-warning-messages-not-related-to-the-changes-i-make-in-my-working-branch) to resolve them.

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by shsagir** [comment]
Learn Build status updates of commit _[abd34b9](https://github.com/akshay9/dataexplorer-docs/commits/abd34b9ad102deda6c8fe437288385b4d7654d46)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[data-explorer/kusto/management/capacitypolicy.md](https://github.com/akshay9/dataexplorer-docs/blob/patch-1/data-explorer/kusto/management/capacitypolicy.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/44fbb50c-a02d-79e7-9b6a-0040a309a8dd/202301060950466686-1564/BuildReport?accessString=0371284994b3b18298f0d008327d4c7cc75ac07050082d0fb9584abee1b10590).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/44fbb50c-a02d-79e7-9b6a-0040a309a8dd?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by Court72** [comment]
@shsagir

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by shsagir** [comment]
#sign-off

**Pull request merged**
