### PR TITLE
Update topnestedoperator.md

### PR DESCRIPTION
**Pull request by daviburg**
Corrected variable name TopNestedClause

### CODE REVIEW

**Comment by PRMerger10** [comment]
@daviburg : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by YaelSchuster** [comment]
#sign-off
(content team on ADX)
@daviburg thanks for your contribution!

**Comment by PRMerger15** [comment]
@YaelSchuster: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by orspod** [comment]
#sign-off

**Pull request merged**
