### PR TITLE
Update how-to-authenticate-with-aad.md

### PR DESCRIPTION
**Pull request by rabenshm**
rename token cache file

### CODE REVIEW

**Comment by PRMerger15** [comment]
@rabenshm : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by cosh** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@cosh: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by shsagir** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@shsagir: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
