### PR TITLE
Change column name "B" to "V" for consistency between examples

### PR DESCRIPTION
**Pull request by SvenAelterman**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@SvenAelterman : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by YaelSchuster** [comment]
Hi @SvenAelterman thanks for contributing to our docs.
Looks good to me.
#sign-off

**Comment by PRMerger7** [comment]
@YaelSchuster: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger15** [comment]
@YaelSchuster: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
