### PR TITLE
Removed comma from ARM sample template json

### PR DESCRIPTION
**Pull request by shinmccold**
In the ADX create cluster & database docs ([https://docs.microsoft.com/en-us/azure/data-explorer/create-cluster-database-resource-manager](url)) it has invalid sample ARM template json because of "**,**" (comma). (see the image below)
invalid_arm_template

Removed comma to make it syntactically correct.

### CODE REVIEW

**Comment by PRMerger4** [comment]
@shinhacker : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by shsagir** [comment]
@pr-review Reviewed and signed off by docs team
#sign-off

**Comment by PRMerger8** [comment]
@shsagir: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
