### PR TITLE
Update ingest-json-formats.md

### PR DESCRIPTION
**Pull request by liualexiang**
update the json mapping sample

### CODE REVIEW

**Comment by PRMerger18** [comment]
@liualexiang : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by vladikbr — APPROVED** [review]

**Comment by vladikbr** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@vladikbr: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by YaelSchuster** [comment]
@vladikbr is on the product team. Please merge.
#sign-off

**Comment by PRMerger12** [comment]
@YaelSchuster: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
