### PR TITLE
Fix PowerShell scripts

### PR DESCRIPTION
**Pull request by michimune**
There were a couple of lines in the PowerShell sample code which need to be fixed. I have confirmed the script after the change worked fine.

### CODE REVIEW

**Comment by PRMerger16** [comment]
@michimune : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Review by docohe — APPROVED** [review]
Thanks!

**Comment by YaelSchuster** [comment]
#sign-off (ADX content team)

**Comment by PRMerger14** [comment]
@YaelSchuster: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by YaelSchuster** [comment]
@michimune thanks so much for your contribution!

**Comment by michimune** [comment]
Thank you!

**Pull request merged**
