### PR TITLE
Update external-tables-managed-identities.md

### PR DESCRIPTION
**Pull request by jbla9028**
fix typo in the merge cmd.

### CODE REVIEW

**Comment by PRMerger15** [comment]
@jbla9028 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by jborsecnik** [comment]
@shsagir, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by YaelSchuster** [comment]
@jbla9028 thanks for noticing that!

Approved by ADX content team

#sign-off

**Comment by PRMerger8** [comment]
@YaelSchuster: I'm sorry - only the author of this article, @shsagir, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by shsagir** [comment]
#sign-off

**Pull request merged**
