### PR TITLE
Update kusto-cli.md

### PR DESCRIPTION
**Pull request by ManojRaheja**
Added link for .Net Core

### CODE REVIEW

**Comment by PRMerger17** [comment]
@ManojRaheja : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
Thanks for your contribution @ManojRaheja - Before this PR is merged, ".Net" should be changed to ".NET" in both instances.

**Comment by YaelSchuster** [comment]
@manojraheja please open PRs in the private repo in the future.

Approved by ADX product team

#sign-off

**Comment by PRMerger12** [comment]
@YaelSchuster: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger4** [comment]
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request merged**
