### PR TITLE
in the same region or subscription?

### PR DESCRIPTION
**Pull request by chwunder**
you are saying in the paragraph above this one, the KV must be in the same region but could be in a different subscription. Now in the paragraph i have edited, you are saying it must be in the same subscription? That´s confusing :-)

### CODE REVIEW

**Comment by PRMerger14** [comment]
@chwunder : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@shsagir : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by shsagir** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@shsagir: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
