### PR TITLE
Vp/governance

### PR DESCRIPTION
**Pull request by vplauzon**
First draft for the governance article in ADX.

### CODE REVIEW

**Comment by PRMerger7** [comment]
@vplauzon : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @vplauzon New content should be submitted in the private repo. Will you create a PR for this content in the private repo? We'll close this PR. Thanks.

**Comment by vplauzon** [comment]
Would be happy to @ktoliver, but I do not have access to the private repo.

**Comment by ktoliver** [comment]
> Would be happy to @ktoliver Kristine Toliver (Aquent LLC) Vendor, but I do not have access to the private repo.

Thanks @vplauzon. I've reopened the PR and sent email.

**Pull request closed without merging**
