### PR TITLE
Document update showing latest portal screenshots

### PR DESCRIPTION
**Pull request by AbhinavDAIICT**
Updated cluster details table to reflect the latest options on the portal in correct order

### CODE REVIEW

**Comment by PRMerger14** [comment]
@AbhinavDAIICT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@AbhinavDAIICT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@AbhinavDAIICT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger4** [comment]
@AbhinavDAIICT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ShannonLeavitt** [comment]
@orspod - Please let us know if you are okay with these changes. After we receive your confirmation, we will need to move the commits to the private repo for validation and staging before we can merge.

#label:"aq-pr-triaged"

**Comment by YaelSchuster** [comment]
@vRachelBell - assigning this to you to review, will discuss offline

**Comment by YaelSchuster** [comment]
Thanks @AbhinavDAIICT we've pulled this into the private repo to validate and merge.

#please-close

**Pull request closed without merging**
