### PR TITLE
M-S-T-Alter table cmd - edited [was #259] - edited

### PR DESCRIPTION
**Pull request by Leybl**

### CODE REVIEW

**Comment by PRMerger8** [comment]
@Leybl : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Jak-MS** [comment]
Hi @Leybl - It looks like you have access to the private repo and PRs that make changes larger than a typo or two should be handled in the private repo. In the future can you submit your commits there? Thanks.

@orspod - can you take a look at this PR? 

***
> Microsoft authors and contributors need to make content contributions through the private repository so the content can be staged and validated by the current validation rules.  
> 
> After you review staging and fix all validation issues, you can tag an author for review or add the sign-off comment to let PR reviewers know that the updates are ready to be merged.  
> 
> Read about [authors working in the public repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master) for more information.  
> 
> If you need help getting set up to work in the private repo, see [How to get to the private repo](https://review.docs.microsoft.com/en-us/help/contribute/contribute-authors-in-public-repo?branch=master#how-to-get-to-the-private-repo). You can also take a look at the [GitHub account setup page](https://review.docs.microsoft.com/en-us/help/contribute/contribute-get-started-setup-github?branch=master) for additional details on making sure you're set up.

**Comment by Leybl** [comment]
Sorry - my mistake.
please refer to #340:

https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/340

**Comment by Leybl** [comment]
#close-pr

**Pull request closed without merging**
