### PR TITLE
Update parseoperator.md

### PR DESCRIPTION
**Pull request by triangularcover**
Fix punctuation in kusto query examples

### CODE REVIEW

**Comment by PRMerger9** [comment]
@triangularcover : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by shsagir** [comment]
@triangularcover Thanks for your feedback. We're submitting your suggestion, and the updated article should be live by tomorrow. Please let us know if there's anything more we can do for you. To follow up on this issue, leave us a comment with an @mention.

**Comment by shsagir** [comment]
FYI: @orspod
#sign-off

**Comment by PRMerger10** [comment]
@shsagir: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by orspod** [comment]
#sign-off

**Pull request merged**
