### PR TITLE
Clarify the function is using radians for input.

### PR DESCRIPTION
**Pull request by rodneykorn**
It can be confusing to not know the units being used for the Sine and Cosine functions. Probably need to update other trig functions also but these are the one I was using.

### CODE REVIEW

**Comment by rodneykorn** [comment]
> ```
> @microsoft-github-policy-service agree [company="Microsoft"]
> ```
> > ```
> > * @microsoft-github-policy-service agree
> > ```
> > 
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> > 
> > ```
> > @microsoft-github-policy-service agree company="Microsoft"
> > ```
> 
> Contributor License Agreement

**Comment by rodneykorn** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by Jak-MS** [comment]
@shsagir 
- Can you review this PR?
- IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by YaelSchuster** [comment]
Hi @rodneykorn thanks so much for making the effort to update this missing information.

**Comment by YaelSchuster** [comment]
Approved by ADX docs

#sign-off

**Comment by shsagir** [comment]
#sign-off

**Pull request merged**
