### PR TITLE
Update ingest-data-kafka.md

### PR DESCRIPTION
**Pull request by anagha-microsoft**

### CODE REVIEW

**Comment by PRMerger16** [comment]
@anagha-microsoft : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
Hi @anagha-microsoft - Substantial content updates should be made in the private repo, so they can be verified on staging and pass quality validations. Would you submit this update in the private repo? We'll close this PR. Thanks.

**Comment by ktoliver** [comment]
Reopening for review. @orspod we can move the commit to the private repo for staging after you review the updates. Thanks.

**Comment by ktoliver** [comment]
Closing per @anagha-microsoft -- thanks.

**Pull request closed without merging**
