### PR TITLE
Update create-cluster-database-powershell.md

### PR DESCRIPTION
**Pull request by aminpashna**
azure poweshell interactive was:
New-AzKustoCluster -ResourceGroupName testrg -Name mykustocluster -Location 'Central US' -Sku D13_v2 -Capacity 10
I tried it and it was complaining about some changes, so I believe the correct one is: 
New-AzKustoCluster -ResourceGroupName testrg -Name mykustocluster -Location westus2 -SkuTier Standard -SkuCapacity 2 -SkuName 'Standard_D11_v2'

### CODE REVIEW

**Comment by PRMerger7** [comment]
@aminpashna : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by Aviv-Yaniv** [comment]
Hey aminpashna

Thank you for noticing!
We will approve the PR

Current docs version is to be updated soon with the new API version

**Comment by YaelSchuster** [comment]
Approved by ADX content and dev team

#sign-off

**Comment by PRMerger-2** [comment]
@YaelSchuster: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
