### PR TITLE
Update power-bi-best-practices.md

### PR DESCRIPTION
**Pull request by KennieNP**

### CODE REVIEW

**Comment by shsagir** [comment]
Learn Build status updates of commit _[4085baa](https://github.com/KennieNP/dataexplorer-docs/commits/4085baab835bf20e79afa30b03968fd50c5b7ddd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[data-explorer/power-bi-best-practices.md](https://github.com/KennieNP/dataexplorer-docs/blob/patch-1/data-explorer/power-bi-best-practices.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/44fbb50c-a02d-79e7-9b6a-0040a309a8dd/202210141605235265-1449/BuildReport?accessString=695893b172f6927788ffa9c024670d01445dd95f37d64629f354de4c36d9d557).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/44fbb50c-a02d-79e7-9b6a-0040a309a8dd?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by jborsecnik** [comment]
@shsagir, 

Can you review the proposed changes? 

IMPORTANT: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by YaelSchuster** [comment]
Cannot merge without signed CLA. @KennieNP please note.

**Comment by shsagir** [comment]
Learn Build status updates of commit _[4085baa](https://github.com/KennieNP/dataexplorer-docs/commits/4085baab835bf20e79afa30b03968fd50c5b7ddd)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[data-explorer/power-bi-best-practices.md](https://github.com/KennieNP/dataexplorer-docs/blob/patch-1/data-explorer/power-bi-best-practices.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/44fbb50c-a02d-79e7-9b6a-0040a309a8dd/202210241417379274-1449/BuildReport?accessString=4a66645e1e0caf9e3d13e3d4a0a454106aa4ee5feaf11204ca1c8c84f923838e).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/44fbb50c-a02d-79e7-9b6a-0040a309a8dd?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

**Comment by Court72** [comment]
@shsagir,

All checks have pased. Could you review this proposed update to your article and enter `#sign-off` in a comment if it's approved for merge?

Thanks!

**Comment by YaelSchuster** [comment]
Approved by ADX content team
#sign-off

**Pull request merged**
