### PR TITLE
Exercise Technical Writing (Ziv)

### PR DESCRIPTION
**Pull request by ZGYMS**
I may have gone too far with this exercise and missed the main point...  I completed it up to the ‘Filtering rows: where’ section.  I would appreciate knowing if I am on the right track before proceeding further. Thanks, Ziv

### CODE REVIEW

**Comment by ShannonLeavitt** [comment]
@ZGYMS - Could you take a moment to [sign the CLA](https://github.com/MicrosoftDocs/dataexplorer-docs/pull/2222#issuecomment-2003086742)?

**Comment by ZGYMS** [comment]
@microsoft-github-policy-service agree [company="Microsoft"]

**Comment by ZGYMS** [comment]
@microsoft-github-policy-service agree

**Comment by Court72** [comment]
@shsagir

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by YaelSchuster** [comment]
#please-close

**Pull request closed without merging**
