### PR TITLE
Update using-diagnostic-logs.md

### PR DESCRIPTION
**Pull request by t-shanigit**
add missing log name

### CODE REVIEW

**Comment by PRMerger14** [comment]
@t-shanigit : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by t-shanigit** [comment]
@YaelSchuster @LeaShallev @kerend

**Review by YaelSchuster — APPROVED** [review]

**Comment by YaelSchuster** [comment]
#sign-off

**Comment by PRMerger14** [comment]
@YaelSchuster: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by orspod** [comment]
#sign-off

**Pull request merged**
