### PR TITLE
Refactor make-series to use new from-to-step syntax

### PR DESCRIPTION
**Pull request by vplauzon**
New syntax is recommended by Adi E.

### CODE REVIEW

**Comment by PRMerger10** [comment]
@vplauzon : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by orspod** [comment]
@vplauzon - thanks for your contribution to our docs.
@adieldar - please review the changes and approve.

**Comment by adieldar** [comment]
Thanks Vincent-Philippe @vplauzon for fixing this. This fix should be also applied to the docs of the other fill functions: series_fill_const, series_fill_forward and series_fill_backward. Can you update the PR?

**Comment by PRMerger16** [comment]
@vplauzon : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@vplauzon : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger16** [comment]
@vplauzon : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger17** [comment]
@vplauzon : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by vplauzon** [comment]
@adieldar, I did changes on the other articles.  Sorry they are all in different commits, I'm using GitHub to edit pages, so I can't bundle them.

**Comment by orspod** [comment]
@adieldar - please approve changes so I can sign off. Thanks!

**Comment by YaelSchuster** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@YaelSchuster: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
