### PR TITLE
ingest-inline.md: Add second allowed syntax

### PR DESCRIPTION
**Pull request by NaridaL**
See the code sample here for an example of that syntax https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/scalar-data-types/dynamic#dynamic-literals

### CODE REVIEW

**Comment by NaridaL** [comment]
I'm having issues figuring out what the actual syntax is. The following results in a syntax error.

```kusto
.ingest inline into table AleonhardTest with (format="multijson") [{"Timestamp":'2015-01-13',
"Trace":"{\"EventType\":\"D##mo\",\"EventValue\":\"Double-quote love!\"}"/*sdas*/}]
```

**Comment by v-dkorn** [comment]
Hi @NaridaL, I'm looking into this for you.

**Comment by Court72** [comment]
@shsagir

Can you review the proposed changes? 

When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

**Comment by v-dkorn** [comment]
@NaridaL what is your use case for using inline ingestions? 

Our team recommends using .set-or-append over .ingest inline. For example:

```
.set-or-append T <|
datatable(d:dynamic)
[
dynamic({"a": 123})
] 
```

**Comment by v-dkorn** [comment]
#please-close

**Comment by NaridaL** [comment]
@v-dkorn why was this closed? I don't have an explicit use case for this, but if it is used in another part of the docs, it should really be documented.

**Pull request closed without merging**
