### PR TITLE
Updated limits on query concurrency limits section

### PR DESCRIPTION
**Pull request by minwal**
We need to make Query throttling policy documentation public, then link it with the above modified concurrency section. Please make following internal docs public -
https://kusto.azurewebsites.net/docs/kusto/management/querythrottlingpolicy.html
https://kusto.azurewebsites.net/docs/kusto/controlCommands/querythrottlingpolicy.html#show-cluster-policy-querythrottling

### CODE REVIEW

**Comment by PRMerger9** [comment]
@minwal : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger10** [comment]
@minwal : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger18** [comment]
@minwal : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by avneraa** [comment]
I believe that the max is 160, so for example if you have 50 nodes, the max concurrency is still a 160. Can you please check it and if it is correct can you update the docs?

**Comment by PRMerger12** [comment]
@minwal : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by minwal** [comment]
> I believe that the max is 160, so for example if you have 50 nodes, the max concurrency is still a 160. Can you please check it and if it is correct can you update the docs?

Confirmed with Yoni, no such restriction. It all depends on multiple factors as documented - cluster SKU/size, complexity of queries, data volumes etc.

**Comment by avneraa** [comment]
> > I believe that the max is 160, so for example if you have 50 nodes, the max concurrency is still a 160. Can you please check it and if it is correct can you update the docs?
> 
> Confirmed with Yoni, no such restriction. It all depends on multiple factors as documented - cluster SKU/size, complexity of queries, data volumes etc.

Oh - I see, your wording is not correct then, you write this: 

"Azure Data Explorer Cluster SKU and size – The default value of the query concurrency limit depends on the cluster SKU **and size(number of cores and nodes in a cluster)**, it is calculated as: `Cores-Per-Node x 10`."  

where in actual it does not depend on the cluster size (number of nodes), just the node type (how many cores the node has), so it does not matter if the cluster has 2 nodes of D14_v2 or a 100 nodes of the same type, it is still going to be 160 concurrent queries limit.

**Comment by PRMerger7** [comment]
@minwal : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
@minwal - Hi. This pull request was opened in the public repo. PMs should work in the private repo, per the Microsoft Docs contributor guide. We'll keep this PR open for review and merge, but in the future, would you make content updates in the private repo? Thanks!

**Comment by minwal** [comment]
Closing this PR as it requires some of the other pre-requisites to be published first then will create new PR.

**Pull request closed without merging**
