### PR TITLE
correct facts in examples.

### PR DESCRIPTION
**Pull request by EdMaurer**
corrected the capitals of the states listed in an example.

### CODE REVIEW

**Comment by PRMerger12** [comment]
@EdMaurer : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by ktoliver** [comment]
#label:"aq-pr-triaged"

**Comment by YaelSchuster** [comment]
@EdMaurer thanks for picking up on that. I guess whomever wrote the example needs a refresher in Geography.

Approved by ADX content team

#sign-off

**Comment by PRMerger8** [comment]
@YaelSchuster: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
