### PR TITLE
- Document existence of export in Web UI.

### PR DESCRIPTION
**Pull request by edburns**
On branch edburns-msft-client-side-export https://github.com/MicrosoftDocs/dataexplorer-docs/issues/102

new file:   data-explorer/media/web-query-data/export-results.png
modified:   data-explorer/web-query-data.md

- Document existence of export in Web UI.

### CODE REVIEW

**Comment by PRMerger13** [comment]
@edburns : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by orspod** [comment]
@edburns - let us know when you are ready to incorporate the changes. The PR is currently in draft format

**Comment by edburns** [comment]
In the absence of a "preview link" facility, I reviewed the rendered changes and they look ready for review, @orspod

**Comment by orspod** [comment]
@edburns - sorry for the delay - there were additional changes in the UI since your PR....
I opened the following PR to incorporate your changes: https://github.com/MicrosoftDocs/dataexplorer-docs-pr/pull/433
thanks for your contribution to docs.

**Pull request closed without merging**
