### PR TITLE
Refactor headers (** with ##)

### PR DESCRIPTION
**Pull request by vplauzon**
Using simple Python script in https://github.com/vplauzon/python/blob/master/refactor-headers-adx-doc/replace-section-headers.py

I've done the folders kusto/query/* only.

What would remains to be done is to have a standard ### Example 1,2,3 or something.  That tends to vary.

### CODE REVIEW

**Comment by orspod** [comment]
@vplauzon - WOW! thanks so much for your contribution to the docs.
Adding @slavikn84, @sloutsky, @zivcaspi to approve the changes.

@vplauzon contributions allow alignment of our query documentation with the rest of docs which use "##" for heading 2 and not **heading**. This change to heading 2 will also result in an internal TOC in the doc which is really helpful to our users. We didn't attempt this change previously since manually changing 357 pages wasn't realistic....

**Comment by sloutsky** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@sloutsky: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by orspod** [comment]
#sign-off

**Comment by orspod** [comment]
#hold-off

**Comment by orspod** [comment]
#sign-off

**Comment by ktoliver** [comment]
Spot-checked from a PR review perspective; looks good.

**Pull request merged**
