### PR TITLE
Update log-reduce-full-fl.md

### PR DESCRIPTION
**Pull request by adieldar**
Bug fix

### CODE REVIEW

**Comment by adieldar** [comment]
#sign-off

**Comment by adieldar** [comment]
Hi @shsagir, fixed a bug. Tried to sign-off but can't, only you can. So please sign-off, thx!

**Comment by shsagir** [comment]
#sign-off

**Comment by shsagir** [comment]
#hold-off

**Comment by v-dkorn** [comment]
@adieldar I'm going to make and merge the changes in the private repo.

#please-close

**Pull request closed without merging**
