### PR TITLE
Add docs about PBI Connector ClientRequestIdPrefix option

### PR DESCRIPTION
**Pull request by saguiitay**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@saguiitay : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by saguiitay** [comment]
@Gabilehner

**Comment by YaelSchuster** [comment]
Hi @saguiitay, for future reference all PRs created by MSFT employees must be opened in the private repo.

**Comment by YaelSchuster** [comment]
Created by ADX dev

#sign-off

**Comment by PRMerger8** [comment]
@YaelSchuster: I'm sorry - only the author of this article, @orspod, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request merged**
