### PR TITLE
adds limitations for dfs endpoint connections

### PR DESCRIPTION
**Pull request by cosh**

### CODE REVIEW

**Comment by shsagir** [comment]
Docs Build status updates of commit _[b2388a7](https://github.com/cosh/dataexplorer-docs/commits/b2388a7ed21e1687a7c819e07432ae0510908f6d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[data-explorer/security-network-managed-private-endpoint-create.md](https://github.com/cosh/dataexplorer-docs/blob/patch-5/data-explorer/security-network-managed-private-endpoint-create.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/44fbb50c-a02d-79e7-9b6a-0040a309a8dd/202208290724548257-1372/BuildReport?accessString=b72636de419c28e6be7b503f9c9ce6aad146ab7bcca39342c8ebf04544fcfaeb).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/44fbb50c-a02d-79e7-9b6a-0040a309a8dd?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the docs.microsoft.com <a href="https://review.docs.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Docs support channel</a></li></ul>

**Review by cosh — COMMENTED** [review]
Adds limitation for dfs connection

**Review by cosh — COMMENTED** [review]
adds limitation for dfs

**Comment by YaelSchuster** [comment]
@cosh can you please check that your SpineEdit extension is working? You've opened this PR on the public repo, which is difficult for us to manage. Please re-open on the private - and let me or Shlomo know if you need any help.

#please-close

**Pull request closed without merging**
