### PR TITLE
Move time series analysis overview to top

### PR DESCRIPTION
**Pull request by loganrosen**
Also adjusting the capitalization to match other TOC items

### CODE REVIEW

**Comment by ktoliver** [comment]
Hi @loganrosen - Updates to TOC files and most content changes should be initiated in the private repository. To access the private repo, add "-pr" in the URL for a specific article. We'll close this PR. Thank you.

CC @rkarlin

**Comment by loganrosen** [comment]
@ktoliver Should I have access to the private repository? I don't appear to, and I don't work on the Data Explorer product (I'm a LinkedIn employee who uses it).

**Comment by ktoliver** [comment]
@loganrosen - Hi, I see you in the Microsoft Outlook address book, so I assumed you were internal to Microsoft. I'll look into this. Meanwhile, I will reopen the PR and assign to @rkarlin. If the update is approved, the commit should be moved to the private repo so the updated TOC can be verified on staging before it is merged.

**Comment by ktoliver** [comment]
@loganrosen - Hi, I will look into it. You appear internal to Microsoft, but... not. Meanwhile, I'll assign the PR to @rkarlin. If the update is approved, the commit should be moved to the private repo so it can be validated on staging before being merged. Thanks.

**Comment by loganrosen** [comment]
Actually, I was just able to join the MicrosoftDocs org via opensource.microsoft.com. I now have access to the private repo. I'll PR my change there instead. :)

**Comment by ktoliver** [comment]
Awesome! Thanks @loganrosen

**Pull request closed without merging**
